// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2cb2ZiZ21LglpDCz9xCfS6oML8ESLJYk',
    appId: '1:616243502406:web:624266251e31a5bd379947',
    messagingSenderId: '616243502406',
    projectId: 'social-app-fe90e',
    authDomain: 'social-app-fe90e.firebaseapp.com',
    storageBucket: 'social-app-fe90e.appspot.com',
    measurementId: 'G-2JKR6EQ211',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHi7N7si98zNyR8IAU_vqbioDcVJMNqlM',
    appId: '1:616243502406:android:e9ee87df080ed48e379947',
    messagingSenderId: '616243502406',
    projectId: 'social-app-fe90e',
    storageBucket: 'social-app-fe90e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJx4M6H0lR8rkGm7dfdS8W6uCXGaEFwXk',
    appId: '1:616243502406:ios:4a05d0b7531861e9379947',
    messagingSenderId: '616243502406',
    projectId: 'social-app-fe90e',
    storageBucket: 'social-app-fe90e.appspot.com',
    androidClientId: '616243502406-ok3a5fo5rrjjh5sk7m68ub9rm7dnil2d.apps.googleusercontent.com',
    iosBundleId: 'com.marcoSoftSolutions.goChat',
  );
}
